### PR TITLE
Bail out if query data undefined

### LINKED ISSUE #2925: Make undefined an illegal cache value (for successful queries)
Please see [this discussion](https://github.com/tannerlinsley/react-query/discussions/2823)

This is an ever-recurring issue that you can't bail out of updates with `setQueryData`. But because the updater function gives you a potentially undefined value (if there is no cache entry for the key yet), TypeScript is very unhappy because you're supposed to create a new cache entry, and there is no "bailing out of it" because react-query actually creates the cache entry _before_ the functional updater of setQueryData is called.

### Proposed solution

As stated [here](https://github.com/tannerlinsley/react-query/discussions/2823#discussioncomment-1562184):

- let's allow the setQueryData functional updater to return undefined
  - signature: T | ((prev: T | undefined) => T | undefined)
  - if `undefined` is returned, we do not create or update the cache entry
  - that means if we have a previous value and `undefined` is returned - `undefined` is _not_ written to the cache, and observers are not informed about that.
  - this is technically breaking if `undefined` is a legit cache entry value for someone

This would be in-ine with what the `initialData` function already does: if `undefined` is returned from that, it is _not_ persisted to the cache.

Also, if a fetch function returns `undefined`, we should:
- transform it to a failed promise (error)
- warn during development mode about it

### PR DESCRIPTION
**Pull request by phatmann**
closes #2925 

@TkDodo here is the wildly simpler PR we have all been hoping for :-)

### CODE REVIEW

File: src/core/queryClient.ts [hunk 1]
```diff
@@ -129,14 +130,28 @@ export class QueryClient {
...
+      return
+    }
+
+    if (!query) {
+      const parsedOptions = parseQueryArgs(queryKey)
+      const defaultedOptions = this.defaultQueryOptions(parsedOptions)
+      query = this.queryCache.build(this, defaultedOptions)
+    }
+
+    return query.setData(data, options)
```
Comment (TkDodo) [inline src/core/queryClient.ts:154]: if we go this way, I think there would be no need for `query.setData` to accept a functional updater, as we now only call it with `data`. That would allow us to get rid of some code in `query.ts` that we have re-introduced here.

However, from our discussion on the other PR, I thought we were going a slightly different route by _disallowing_ `undefined` as a cache value altogether.

It is a common source of error that people do not return anything from their `queryFn` because they do things like:

```
axios.get('/api').then(result => console.log(result))
```

which then returns `Promise<void>`. Of course, TypeScript helps :)

But I like the current approach much more because it's simpler. So how about we do:

- the proposed change here to `query.setData`
- add a dev mode error logging here if we get `undefined` just to make people aware that this is disallowed
https://github.com/tannerlinsley/react-query/blob/c0fc916cb3e7d32a05e9356b2f1359c3cd5de573/src/core/query.ts#L446
- try to tweak the typescript types to disallow `undefined` for `TData` on type level - if that's possible. `null` should still be allowed though.
- we'd need to update the docs (migration guide), but I can do that too if you want

Comment (phatmann) [reply src/core/queryClient.ts:154]: @TkDodo If I understand you correctly, the changes that I made so far is good. That is, if `setQueryData` is passed undefined data or a function that returns undefined, bail out. We just need additional changes to prevent undefined being written to the cache. Per #2925:

> Also, if a fetch function returns undefined, we should:
> * transform it to a failed promise (error)
> * warn during development mode about it

That is, I need to modify `setData` as you propose above (including removing extra functional update handling.)

I will also look into the type change.

I will look at the docs and see if I can update them satisfactorily.

Comment (phatmann) [reply src/core/queryClient.ts:154]: Looking at your comments again, I believe you are proposing to _not_ fail a query when the queryFn returns undefined, but instead to bail out. This is what I tried before, and I discovered it breaks clients that are expecting the query status to change as a result of a fetch. I recommend we stick with your original proposal and fail the query if the queryFn returns undefined.

Comment (TkDodo) [reply src/core/queryClient.ts:154]: Transforming to error is fine for me 👍

**Comment by phatmann** [comment]
@TkDodo The checks failed due to a TS error in useQueries.test.tsx. However, I am not seeing the error on my machine, and the line number in the error is for the generated JS code. Any idea what I need to do to reproduce it?

File: src/core/queryClient.ts (hunk 1 above)
Comment (TkDodo) [inline src/core/queryClient.ts:154]: looking at this once more, I don't think we need the `if` guard:

```suggestion
const parsedOptions = parseQueryArgs(queryKey)
const defaultedOptions = this.defaultQueryOptions(parsedOptions)
return this.queryCache
  .build(this, defaultedOptions)
  .setData(data, options)
```

File: src/core/query.ts [hunk 2]
```diff
@@ -219,14 +217,19 @@ export class Query<
...
-  ): TData {
-    const prevData = this.state.data
+  setData(data: TData, options?: SetDataOptions): TData {
+    if (typeof data === 'undefined') {
+      const message = 'Cache data cannot be undefined'
+      getLogger().error(message)
+      const error = new Error(message) as any
+      this.dispatch({
+        type: 'error',
+        error,
```
Comment (TkDodo) [inline src/core/query.ts:227]: my idea was to _not_ do this in `setData`, but keep `setData` to only accept `TData` and do the transformation on the only call-side:

https://github.com/tannerlinsley/react-query/blob/c0fc916cb3e7d32a05e9356b2f1359c3cd5de573/src/core/query.ts#L445-L446

there we could do the check and then:
- extract the `onError` function of the retrier to it's own function
- just call `onError` with the newly created error. That would:
  - dispatch to error state
  - already does the logging in dev mode for us:
https://github.com/tannerlinsley/react-query/blob/c0fc916cb3e7d32a05e9356b2f1359c3cd5de573/src/core/query.ts#L470-L472

**Comment by TkDodo** [comment]
> @TkDodo The checks failed due to a TS error in useQueries.test.tsx. However, I am not seeing the error on my machine, and the line number in the error is for the generated JS code. Any idea what I need to do to reproduce it?

that error is weird indeed. I will have to check it out locally, too.

**Comment by phatmann** [comment]
@TkDodo I see that I again misread your earlier comments:

> The proposed change here to query.setData

You meant removing the functional handling. **Got it.**

> add a dev mode error logging here if we get undefined just to make people aware that this is disallowed

By "here" you meant [query.ts at line 446](https://github.com/tannerlinsley/react-query/blob/c0fc916cb3e7d32a05e9356b2f1359c3cd5de573/src/core/query.ts#L446). **Got it.**

File: src/core/queryClient.ts (hunk 1 above)
Comment (phatmann) [reply src/core/queryClient.ts:154]: Right, since we did not have the guard before.

File: src/core/queryClient.ts [hunk 3]
```diff
@@ -129,14 +130,28 @@ export class QueryClient {
...
-  ): TData {
-    const parsedOptions = parseQueryArgs(queryKey)
-    const defaultedOptions = this.defaultQueryOptions(parsedOptions)
-    return this.queryCache
-      .build(this, defaultedOptions)
-      .setData(updater, options)
+  ): TData | undefined {
+    if (typeof updater === 'undefined') {
+      return undefined
+    }
```
[the remark this answers is not in the document]
Comment (phatmann) [reply src/core/queryClient.ts:138]: Makes sense. Will update code.

File: src/core/query.ts (hunk 2 above)
Comment (phatmann) [reply src/core/query.ts:227]: Sounds way better On it.

**Comment by phatmann** [comment]
@TkDodo I made all the changes you requested.

File: src/core/query.ts [hunk 4]
```diff
@@ -450,6 +447,12 @@ export class Query<
       fn: context.fetchFn as () => TData,
       abort: abortController?.abort?.bind(abortController),
       onSuccess: data => {
+        if (typeof data === 'undefined') {
+          const error = new Error('Query data cannot be undefined') as any
+          this.onError(error)
```
Comment (TkDodo) [inline src/core/query.ts:452]: does this work?

```suggestion
          this.onError(new Error('Query data cannot be undefined') as TError)
```

File: src/core/query.ts [hunk 5]
```diff
@@ -460,28 +463,7 @@ export class Query<
...
-          // Log error
-          getLogger().error(error)
-        }
-
-        // Remove query after fetching if cache time is 0
-        if (this.cacheTime === 0) {
-          this.optionalRemove()
-        }
-      },
+      onError: this.onError,
```
Comment (TkDodo) [inline src/core/query.ts:466]: it doesn't have to live on the `this` scope, I think that is too wide. Also binding comes with an overhead in bundle size I believe. It was an inline function before, so I think it can just be:

`const onError: (error: TError | { silent?: boolean }) => ...`

defined right above `this.retryer = new Retryer({`

File: src/core/queryClient.ts [hunk 6]
```diff
@@ -129,14 +130,21 @@ export class QueryClient {
 
   setQueryData<TData>(
     queryKey: QueryKey,
-    updater: Updater<TData | undefined, TData>,
+    updater: Updater<TData | undefined, TData> | undefined,
     options?: SetDataOptions
-  ): TData {
+  ): TData | undefined {
+    let query = this.queryCache.find<TData>(queryKey)
```
Comment (TkDodo) [inline src/core/queryClient.ts:136]: can be `const` now:

```suggestion
    const query = this.queryCache.find<TData>(queryKey)
```

File: src/core/queryClient.ts [hunk 7]
```diff
@@ -129,14 +130,21 @@ export class QueryClient {
...
+    const prevData = query?.state.data
+    const data = functionalUpdate(updater, prevData)
+
+    if (typeof data === 'undefined') {
+      return
```
Comment (TkDodo) [inline src/core/queryClient.ts:141]: just to be explicit and consistent with the rest of the codebase:

```suggestion
      return undefined
```

File: src/core/queryClient.ts [hunk 8]
```diff
@@ -129,14 +130,21 @@ export class QueryClient {
...
+    }
+
     const parsedOptions = parseQueryArgs(queryKey)
     const defaultedOptions = this.defaultQueryOptions(parsedOptions)
-    return this.queryCache
-      .build(this, defaultedOptions)
-      .setData(updater, options)
+    query = this.queryCache.build(this, defaultedOptions)
+    return query.setData(data, options)
```
Comment (TkDodo) [inline src/core/queryClient.ts:147]: there is no need to reassign to `query` here. We can just do:

```
return this.queryCache.build(this, defaultedOptions).setData(data, options)
```

**Review by TkDodo — COMMENTED** [review]
looks really good! Just when I commented about `new Retryer`, I realized that this PR goes to `master` and not `alpha`, which is our v4 branch (I noticed because I refactored retryer to a function 😅). Since this is a breaking change we want this for v4 please. Can you rebase that PR to v4 ? Thanks 🙏

File: src/core/query.ts (hunk 4 above)
Comment (phatmann) [reply src/core/query.ts:452]: I tried that before. TS says:
> Conversion of type 'Error' to type 'TError' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  'TError' could be instantiated with an arbitrary type which could be unrelated to 'Error'.

So I need to cast to `any`. This makes sense, since errors coming in via try/catch are of type `any` (or `unknown` in newer TS versions). I wish JS had a real base Error type. Oh well.

Comment (TkDodo) [reply src/core/query.ts]: yep, TS is right here. The user can specify anything as `TError`, for example:

```
const { error } = useQuery<number, string>('key', () => Promise.resolve(5))

error?.toUppercase()
```

in that example, they would expect `error` to be a `string` - which it may or may not be. They would be in for a surprise if they then get an `Error`. We do the same thing already if `select` throws an error - we transform to `Error` state.

There are bunch of things we could do:
- ensure that `TError extends Error`. But you can reject a promise with non-Errors, too.
- remove the possibility to type `TError` completely and just always use `unknown`, which is the only "safe" thing to do. That would be pretty breaking for TS users though.

Jus thinking out loud. Nothing we need to do on this PR, the `any` cast is fine :)

**Comment by phatmann** [comment]
@TkDodo when I try to force push the rebased branch, I get this error:

> ! [remote rejected] pr/set-query-data-undefined-bail-out -> pr/set-query-data-undefined-bail-out (refusing to allow an OAuth App to create or update workflow `.github/workflows/test-and-publish.yml` without `workflow` scope)

Should I open a new PR and close this one?

**Comment by phatmann** [comment]
@TkDodo actually I cannot push my branch at all. Nothing to do with the PR. Some workflow changes must have crept into branch, will see if I can find them.

**Comment by phatmann** [comment]
@TkDodo this is apparently a [VS Code Github auth issue](https://stackoverflow.com/questions/64059610/how-to-resolve-refusing-to-allow-an-oauth-app-to-create-or-update-workflow-on). Will fix and push ASAP.

**Comment by phatmann** [comment]
@TkDodo changes are all in and rebased to alpha.

(I just had to switch to using SSH URL ☺️ )

**Comment by phatmann** [comment]
By using this command in the failing test above

> npm run test:types && npm run test:format && npm run test:eslint && jest

I can see the error. Looking into it.

**Review by TkDodo — APPROVED** [review]
❤️ it, thank you 🙇

**Comment by phatmann** [comment]
@TkDodo Tests are all passing now

**Comment by TkDodo** [comment]
> @TkDodo Tests are all passing now

oh nice! That was a sneak `return undefined` in that test from the queryFn 😅 . I guess that shows that types are now catching this :)

I'll add some documentation to the upgrade guide and then we can ship this - thank you so much for this 🙏❤️

File: docs/src/pages/guides/migrating-to-react-query-4.md [hunk 9]
```diff
@@ -245,6 +245,21 @@ Types now require using TypeScript v4.1 or greater
...
+### Undefined is an illegale cache value for successful queries
+
+In order to make bailing out of updates possible by returning `undefined`, we had to make `undefined` an illegal cache value. This is in-line with other concepts of react-query, for example, returning `undefined` from the [initialData function](guides/initial-query-data#initial-data-function) will also _not_ set data.
+
+Further, it is an easy bug to produce `Promise<void>` by adding logging in the queryFn:
+
+```js
+useQuery(
+  ['key'],
+  () => axios.get(url).then(result => console.log(result.data)
```
Comment (TkDodo) [inline docs/src/pages/guides/migrating-to-react-query-4.md:257]:
```suggestion
  () => axios.get(url).then(result => console.log(result.data))
```

**Comment by TkDodo** [comment]
@phatmann I missed that we are now still having lots of log statements during the tests:

Screenshot 2022-02-10 at 15 32 44

could you check from which tests these are coming from?

**Comment by TkDodo** [comment]
I fixed it here: f6a6ae3f
