### PR TITLE
fix(devtools): serialize bigint types

### LINKED ISSUE #3082: React Query Devtools cannot serialize BigInt type
**Describe the bug**
One of the models that I am caching with React Query is a BigInt type. Unfortunately, when I try and inspect the data in the devtools explorer, I get an uncaught error: `TypeError: Do not know how to serialize a BigInt`.

**To Reproduce**
1. Add an object using a BigInt type to the query cache
2. Open the Devtools
3. Select the query in the browser to inspect the data
4. See the error

**Expected behavior**
I should be able to view properly serialised data in the devtools browser.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Pop_OS 21.04
 - Browser: Chrome
 - Version: 94

**Additional context**
The error can be traced to this line: https://github.com/tannerlinsley/react-query/blob/master/src/devtools/Explorer.tsx#L112. If there's a reason that the data is being stringified, then hopefully there's a way to keep doing it, but there are data types which cannot be parsed by JSON.stringify. There may be other options, such as https://github.com/blitz-js/superjson but I understand that would add further complexity.

### PR DESCRIPTION
**Pull request by HenriqueDerosa**
closes #3082 

### Detail
I detected the issue `TypeError: Do not know how to serialize a BigInt` was caused by `JSON.stringify` in the devtools explorer. I created a separate function so I could also write a test. 

This is my first contribution here, so please, let me know how I can improve this implementation. 😄

### CODE REVIEW

File: src/devtools/utils.ts [hunk 1]
```diff
@@ -123,6 +123,19 @@ export function useSafeState<T>(initialState: T): [T, (value: T) => void] {
   return [state, safeSetState]
 }
 
+/**
+ * Displays a string regardless the type of the data
+ * @param {any} value Value to be stringified
+ */
+ export const displayValue = (value: any) => {
```
Comment (TkDodo) [inline src/devtools/utils.ts:130]: let's please use `unknown` instead of `any`:

```suggestion
/**
 * Displays a string regardless the type of the data
 * @param {any} value Value to be stringified
 */
 export const displayValue = (value: unknown) => {
```

File: src/devtools/tests/Explorer.test.tsx [hunk 2]
```diff
@@ -54,4 +55,8 @@ describe('Explorer', () => {
       expect(toggleExpanded).toHaveBeenCalledTimes(1)
     })
   })
+
+  it('when the value is a BigInt', () => {
+    expect(displayValue(BigInt(1))).toBe('"1n"')
+  })
```
Comment (TkDodo) [inline src/devtools/tests/Explorer.test.tsx:61]: please put this in it's own `describe('displayValue')` block, and add at least one test that also tests for non-big-int please.

File: src/devtools/utils.ts [hunk 3]
```diff
@@ -123,6 +123,19 @@ export function useSafeState<T>(initialState: T): [T, (value: T) => void] {
...
+  let newValue = value
+  const name = Object.getOwnPropertyNames(Object(value))
+  if (typeof value === 'bigint') {
+    newValue = `${value.toString()}n`
+  }
+  return JSON.stringify(newValue, name)
```
Comment (TkDodo) [inline src/devtools/utils.ts:136]: how about:

```
const name = Object.getOwnPropertyNames(Object(value))
const newValue = typeof value === 'bigint' ? `${value.toString()}n` : value


return JSON.stringify(newValue, name)
```

**Review by TkDodo — COMMENTED** [review]
thank you for this contribution - it looks good already 👍. Just some minor comments from my side

**Comment by TkDodo** [comment]
also, prettier formatting is off:

```
$ prettier "{.,src,src/**,example/src,example/src/**,types}/*.{md,js,jsx,ts,tsx,json}" --check
Checking formatting...
[warn] src/devtools/utils.ts
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
error Command failed with exit code 1.
```

**Review by TkDodo — APPROVED** [review]
